apiVersion: v1
kind: Service
metadata:
  name: igor
  labels:
    component: igor
spec:
  ports:
    - port: 8088
      name: igor
    - port: 8080
      name: jenkins-master
    - port: 50000
      name: jenkins-agent
  selector:
    component: igor
