apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front50
  labels:
    component: front50
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap/spinnaker-config.yaml") . | sha256sum }}
      labels:
        component: front50
    spec:
      containers:
        - image: gcr.io/spinnaker-marketplace/front50:0.4.1-72
          name: front50
          ports:
            - containerPort: 8080
              name: front50
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: spinnaker-config
            - mountPath: /root/.aws
              name: s3-config
            {{ if .Values.gcs.enabled }}
            - mountPath: /root/.kube
              name: gcs
            {{ end }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 1
      volumes:
        - name: spinnaker-config
          configMap:
            name: spinnaker-config
        - name: s3-config
          configMap:
            name: s3-config
        {{ if .Values.gcs.enabled }}
        - name: gcs
          secret:
            secretName: gcs
        {{ end }}
