apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: igor
  labels:
    component: igor
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap/spinnaker-config.yaml") . | sha256sum }}
      labels:
        component: igor
    spec:
      containers:
        - image: gcr.io/spinnaker-marketplace/igor:0.4.0-72
          name: igor
          ports:
            - containerPort: 8088
              name: igor
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: spinnaker-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8088
            initialDelaySeconds: 20
            timeoutSeconds: 1
      volumes:
      - name: spinnaker-config
        configMap:
          name: spinnaker-config
