apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ""
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        backend:
          # TODO
          serviceName: {{ template "fullname" . }}-deck
          servicePort: 9000
