# This example is from https://docs.google.com/document/d/1cLPGweVEYrVqQvBLJg6sxV-TrE5Rm2MNOBA_cxZP2WU/edit#heading=h.dr88tktf0e99

apiVersion: manifest.k8s.io/v1alpha1
kind: Manifest
metadata:
  name: test-infra-mungebot
description: Mungebot config for test-infra repo
namePrefix: kinflate-spinnaker-
# Labels to add to all objects and selectors.
# These labels would also be used to form the selector for apply --prune
# Named differently than “labels” to avoid confusion with metadata for this object
objectLabels:
  app: kinflate-spinnaker
  org: kubernetes
objectAnnotations:
  note: This is a test annotation
resources:
- ../../package
#These are strategic merge patch overlays in the form of API resources
patches:
- deployment/deployment.yaml
# Uncomment this to enable gcs
#- secrets/gcs.yaml
# Uncomment this to enable gcr as registry
#- secrets/registry.yaml
#There could also be configmaps in Base, which would make these overlays
#configmaps:
#- type: file
#  namePrefix: s3-config
#  files:
#  - configmaps/credentials
#There could be secrets in Base, if just using a fork/rebase workflow
secrets:
- type: tls
  namePrefix: app-tls
  tls:
    certFile: secret/tls.cert
    keyFile: secret/tls.key
recursive: false
prune: true # I’d make this the default
