{{ if .Values.gcs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: gcs
  labels:
    component: clouddriver
type: Opaque
data:
  account.json: {{ default "" .Values.gcs.jsonKey | b64enc | quote }}
{{ end }}