apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: clouddriver
spec:
  template:
    spec:
      containers:
        - image: gcr.io/spinnaker-marketplace/clouddriver:0.5.0-72 # you can change the image here.
          name: clouddriver
