apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deck
spec:
  template:
    spec:
      containers:
        - image: gcr.io/spinnaker-marketplace/deck:1.3.0-72 # you can change the image here.
          name: deck
