apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo
spec:
  template:
    spec:
      containers:
        - image: gcr.io/spinnaker-marketplace/echo:0.4.0-72 # you can change the image here.
          name: echo
