apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gate
spec:
  template:
    spec:
      containers:
        - image: gcr.io/spinnaker-marketplace/gate:0.5.0-72 # you can change the image here.
          name: gate
