apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: igor
spec:
  template:
    spec:
      containers:
        - image: gcr.io/spinnaker-marketplace/igor:0.4.0-72 # you can change the image here.
          name: igor
