apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orca
spec:
  template:
    spec:
      containers:
        - image: gcr.io/spinnaker-marketplace/orca:0.5.0-72 # you can change the image here.
          name: orca
